export const API_VERSION = 1;
export const TVC_APP_PROOF_SCHEME = "SIGNATURE_SCHEME_EPHEMERAL_KEY_P256";
export const CLIENT_ED25519_DERIVATION_SUITE = "zolana-ed25519-role-expansion-v1";
export const MAX_SOLANA_TRANSACTION_BYTES = 1_232;

export const REQUEST_DIGEST_DOMAIN = "ZOLANA_TVC_REQUEST_V1";
export const CLIENT_AUTH_DOMAIN = "ZOLANA_TVC_CLIENT_AUTH_V1";
export const RESULT_DIGEST_DOMAIN = "ZOLANA_TVC_RESULT_V1";
export const ARTIFACT_DIGEST_DOMAIN = "ZOLANA_TVC_ARTIFACT_V1";
export const WALLET_ID_HASH_DOMAIN = "ZOLANA_TVC_WALLET_ID_V1";
export const REQUEST_ID_HASH_DOMAIN = "ZOLANA_TVC_REQUEST_ID_V1";
export const STATE_COMMITMENT_DOMAIN = "ZOLANA_TVC_STATE_COMMITMENT_V1";
export const RELEASE_POLICY_DOMAIN = "ZOLANA_TVC_RELEASE_POLICY_V1";
export const TURNKEY_EVIDENCE_DIGEST_DOMAIN = "ZOLANA_TVC_TURNKEY_EVIDENCE_V1";
export const STATE_DIGEST_DOMAIN = "ZOLANA_TVC_STATE_DIGEST_V1";
export const OWNER_AUTH_DOMAIN = "ZOLANA_TVC_OWNER_AUTH_V1";
export const OWNER_AUTH_EVIDENCE_DOMAIN = "ZOLANA_TVC_OWNER_AUTH_EVIDENCE_V1";
export const PROVISIONING_AUTH_DOMAIN = "ZOLANA_TVC_PROVISIONING_AUTH_V1";
export const ROTATION_AUTH_DOMAIN = "ZOLANA_TVC_ROTATION_AUTH_V1";
export const ACTIVITY_ID_HASH_DOMAIN = "ZOLANA_TVC_ACTIVITY_ID_V1";
export const RELEASE_CHANNEL_DOMAIN = "ZOLANA_TVC_RELEASE_CHANNEL_V1";
export const RECOVERY_INTENT_DOMAIN = "ZOLANA_TVC_RECOVERY_INTENT_V1";
export const QUORUM_ROTATION_DOMAIN = "ZOLANA_TVC_QUORUM_ROTATION_V1";

export const QOS_P256_PUBLIC_LEN = 130;
export const SEC1_UNCOMPRESSED_LEN = 65;
export const RAW_P256_SIGNATURE_LEN = 64;
export const QOS_ENCRYPTION_HMAC_MESSAGE = "qos_encryption_hmac_message";
